### ISSUE TITLE
Make download&install messages persistent

### ISSUE THREAD

**Issue by brusherru** [xodio/xod#1550] opened 2018-11-15 10:10 UTC
To allow a user to notice and respond to a message that requires action, let's make such messages persistent:
- Update available
- Install packages and toolchains
- Install arduino libraries

**Comment by knopki** [comment] 2018-11-15 10:18
ARDUINO_DEPENDENCIES_MISSING (Arduino dependencies missing) is fixed in #1548

**Comment by nkrkv** [comment] 2019-02-11 09:22
Duplicate of #1613 which is closed already by #1614

**Closed by nkrkv** 2019-02-11 09:22 UTC
Labels: s:client, t:tweak
