### ISSUE TITLE
xod folder in home directory is not hidden

### ISSUE THREAD

**Issue by grahas** [xodio/xod#1768] opened 2019-04-22 16:51 UTC
### Environment

* Scope: desktop IDE
* Version: 0.29.1 
* OS: macOS Mojave 10.14.4
* Machine: i5, 8 GB RAM

### Steps to reproduce

1.  New install of xod
2.  From terminal list home directory
3.  xod directory should be .xod directory I think.

### Expected behavior

Shouldn't be able to see the program files, by default they should be hidden.

### Actual behavior

xod folder is showing up in home directory

![Screen Shot 2019-04-22 at 10 46 09 AM](https://user-images.githubusercontent.com/8950797/56512348-57d2c100-64ec-11e9-9ba6-c7581f1f01e0.png)

### How to fix 
Directory should be generated as .xod. Might be able to execute "mv xod .xod". Didn't want to do that incase it breaks a path. Might be faster for someone else with the development environment already setup to fix.

**Comment by nkrkv** [comment] 2019-04-23 14:00
Hello! This is by design. Other software does this as well. Arduino IDE creates `~/Arduino` to store sketches, OBS Studio creates `~/Recordings`, Telegram creates `~/Downloads/Telegram Desktop`, etc. XOD creates `~/xod` as the default workspace.

If you don’t like it, hit File → Switch Workspace and choose any other directory like `~/.xod`, `~/.local/share/xod`, or whatever makes sense.

I’m closing the issue. Feel free to re-open if you believe this is an insufficient solution.

**Closed by nkrkv** 2019-04-23 14:00 UTC
Labels: t:bug, triage
