### ISSUE TITLE
Simulation on limited net.

### ISSUE THREAD

**Issue by gc2654** [xodio/xod#1776] opened 2019-05-13 06:20 UTC
### Environment

* Scope: desktop IDE
* Version: 0.29.1 
* OS: Windows 7
* Machine: i3, 4 GB RAM

### Steps to reproduce
 simulation

### Console output 

Generating C++ code for simulation…
Building…
request to https://api.xod.io/compile/enqueue failed, reason: self signed certificate in certificate chain.

### How to fix 

Probability my firewall that has limited authorized, cause that. 

Desktop IDE may be do simulation on machine without network.

**Comment by nkrkv** [comment] 2019-05-13 09:35
The simulation requires working internet access because the compilation happens in the XOD cloud. It is done in this way to guarantee your PC security (code sandboxing) and proper complex toolchain setup (Emscripten).

The error shown is indeed about some PC or router limitations. Make sure the access to *.xod.io is granted to use simulation.

I’m closing the issue. Feel free to re-open it if you believe the problem is in XOD.

**Closed by nkrkv** 2019-05-13 09:35 UTC
Labels: t:bug, triage
