### ISSUE TITLE
Bug, has more than 7 outputs

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1553] opened 2018-11-18 06:45 UTC
### Console output 

```
Transpiling...
Error
Native node @/4017-mod has more than 7 outputs
The error has no formatter, which is a bug. Report the issue to XOD developers.
```

[CD4017.zip](https://github.com/xodio/xod/files/2592563/CD4017.zip)

**Comment by nkrkv** [comment] 2018-11-19 10:12
Duplicate of #1545

**Closed by nkrkv** 2018-11-19 10:12 UTC
